version: '3.8'
services:
  app:
    build: .
    container_name: ae-project
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - default
networks:
  default:
    driver: bridge 